#!/bin/bash
while true
do
echo "==============="
echo "   Pac-Man     "
echo "==============="
echo "1) Aggiorna"
echo "2) Installa"
echo "3) Rimuovi"
echo "4) Pacchetti installati"
echo "5) Pacchetti orfani"
echo "6) Pulisce l'intera cache"
echo -e "\n"
echo "Premi u per uscire "
echo -e "\n"
read -p "Scegli: " answer
case "$answer" in
1)  sudo pacman -Syu ;;
2)  clear
    read -p "Nome del pacchetto da installare: " pkg
    sudo pacman -S $pkg
    clear
    continue
    ;;
3)  clear
    read -p "Nome del pacchetto da rimuovere: " pkg
    sudo pacman -Rs $pkg
    clear
    continue
    ;;
4) pacman -Q ;;
5) if pacman -Qdt &> /dev/null; then
    echo  "Rimozione dei pacchetti obsoleti e delle dipendenze..."
    pacman -Qdt | awk '{print $1}' | sudo pacman -Rns -
else
    echo  "Nessun pacchetto obsoleto da rimuovere."
    fi
    continue
    ;;
6)  sudo pacman -Scc ;;
u)  exit ;;
*)  clear
    continue
esac
done
